timezone: America/New_York
title: The Alley | Makerspace
collections:
  alley_crew:
    output: false
  advisors:
    output: false
  projects:
    output: true
  wikis:
    output: true
  events:
    output: true

facebook_url: https://www.facebook.com/makerspacemtu/
twitter_url: https://twitter.com/makerspacemtu
instagram_url: https://instagram.com/makerspacemtu
discord_url: https://discord.gg/rwchwXNqWB
email_address: makerspace@mtu.edu
email_updates_url: http://eepurl.com/bKQAsf
alley_reserve_form_url: https://forms.gle/6mRoFRyugN2UaAiu8
training_request_url: https://forms.gle/CN2VsJg6EPfAErtn6

